name: Python Linting and SSH Deployment

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9.14
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.14'

    - name: Install dependencies for linting
      run: |
        python3.9 -m pip install --upgrade pip
        pip3.9 install flake8

    - name: Run linting with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Deploy to ARM Server via SSH and rsync
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "./"
        target: "${{ secrets.DEPLOY_PATH }}"
        script: |
          # 서버에서 실행될 명령어
          
          # 1. 배포 경로로 이동
          cd ${{ secrets.DEPLOY_PATH }}
          
          # 2. 필요한 경우 가상 환경(venv)에 라이브러리 설치 또는 업데이트
          # python3.9 -m venv venv
          # source venv/bin/activate
          # pip3.9 install -r requirements.txt
          
          # 3. 애플리케이션 재시작
          # 예를 들어 Gunicorn 서비스를 재시작하는 명령어
          # sudo systemctl restart lawn-todo-service